name: math-project
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - matplotlib
  - pillow
  - pip
  - setuptools
  - wheel
  - python-dateutil
  - pyparsing
  - packaging
  - jupyterlab
  - scipy
  - pandas
  - scikit-learn
